# akita conda runner uses the following image by default:
# image: continuumio/miniconda3:4.9.2

stages:
  - test
  - build
  - deploy

workflow:
  rules:
    # If `$FORCE_GITLAB_CI` is set, create a pipeline.
    - if: '$FORCE_GITLAB_CI'
    # For merge requests, create a pipeline.
    - if: '$CI_MERGE_REQUEST_IID'
    # For `main` branch, create a pipeline (this includes on schedules, pushes, merges, etc.).
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    # For tags, create a pipeline.
    - if: '$CI_COMMIT_TAG'
    # For branches starting with 'doc/' don't create a pipeline
    - if: '$CI_COMMIT_BRANCH =~ /^doc\//'
      when: never

default:
  tags:
    - akita
    - conda
  before_script:
    - export PIP_CACHE_DIR="/opt/cache/pip"
    - echo "Setting up conda environment and installing dependencies"
    - conda create -y -n gutentag python=${PYTHON_VERSION:-3.7}
    - source activate gutentag
    - pip install -r requirements.txt
    - python --version

test:
  stage: test
  interruptible: true
  script:
    - python setup.py typecheck
    - python setup.py test
  artifacts:
    reports:
      cobertura: coverage.xml
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.7", "3.8", "3.9"]

build:
  stage: build
  only:
    - tags
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*.tar.gz
      - dist/*.whl

deploy:
  stage: deploy
  only:
    - tags
  script:
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url https://gitlab.hpi.de/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
    - TWINE_PASSWORD=${PYPI_API_TOKEN} TWINE_USERNAME=__token__ python -m twine upload --repository pypi dist/*
